version:  '3.3'
services:
    database:
        build:
          context: ./docker/database
        environment:
          - MYSQL_DATABASE=${DATABASE_NAME}
          - MYSQL_USER=${DATABASE_USER}
          - MYSQL_PASSWORD=${DATABASE_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
          - "3306:3306"
        volumes:
          - ./docker/database/data:/var/lib/mysql
    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './apps/test/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on:
            - php
    php:
       build:
           context: .
           dockerfile: docker/php/Dockerfile
       volumes:
           - './apps/test/:/usr/src/app'
       restart: on-failure
       env_file:
           - .env
       user: 1000:1000
       depends_on:
           - database
